// front/src/pages/Login.jsx
import React, { useState, useEffect } from 'react';
import Navbar from '../components/Navbar/navbar';
import axios from 'axios';
import { useLocation, useNavigate, Navigate } from 'react-router-dom';
import ProfilePage from './ProfilePage';
import LoginForm from '../components/Login/login';
import Footer from '../components/Footer/footer';

export default function Login() {
    const navigate = useNavigate();
    const location = useLocation();

    const [username, setUserName] = useState();
    const [password, setPassword] = useState();
    const [user, setUser] = useState()
    const [error, setError] = useState();

    const cred = {
        username: username,
        password: password
    };

    useEffect(() => {
        const loggedInUser = localStorage.getItem("token");
        if (loggedInUser) {
            const foundUser = loggedInUser;
            setUser(foundUser);
            console.log(foundUser);
        }
    }, []);

    async function handleSubmit(e) {
        e.preventDefault();
        axios.post('https://site212224.tw.cs.unibo.it/auth/login/user', {
            username: cred.username,
            password: cred.password
        })
            .then((res) => {
                console.log(res);
                localStorage.setItem("username", cred.username)
                localStorage.setItem("token", res.data.authority)


                //permette di tornare nella pagina che ti ha reindireizzato alla pagina di login
                if (location.state?.from) {
                    navigate(location.state.from)
                }
                else {
                    navigate('/account')
                }
            }, (err) => {
                setError('Invalid Username or Password')
            });
    }

    // se c'è uno user verrà mostrato il profilo
    if (user) {
        return <div>
            < ProfilePage />
        </div>;
    }

    // altrimenti viene mostrata la pagian di login
    return (
        <div>
            <Navbar />
            <LoginForm />
            <Footer />

                <h1>Please Log In DIOACN</h1>
                <form onSubmit={handleSubmit}>
                    <label>
                        <p>Username</p>
                        <input type="text" onChange={e => setUserName(e.target.value)} />
                    </label>
                    <label>
                        <p>Password</p>
                        <input type="password" onChange={e => setPassword(e.target.value)} />
                    </label>
                    <div>
                        <button type="submit">Submit</button>
                    </div>
                </form>
                {error?<div>{error}</div>:null} 
            </div>
    )
}

// game/src/views/Login.vue
<template>
  <main>
  <div class="text-center">
    <form class="form-signin" @submit.prevent="handleSubmit">
    <h3>Login</h3>

      <div class="form-group">
        <label>Username</label>
        <input type="text" class="form-control" v-model="username" placeholder="Username" />
      </div>

      <div class="form-group">
        <label>Password</label>
        <input type="password" class="form-control" v-model="password" placeholder="Password" />
        <p v-if="error.length>0" style="color:red">{{error}}</p>
      </div>
      <button class="btn btn-primary" style="background-color: var(--dark-alt); border: 1px solid var(--dark)">Login</button>
    </form>
  </div>
  </main>
</template>

<script>
import axios from "axios";
export default {
  name: "vueLogin",
  data(){
    return{
      username:'',
      password:'',
      error:'',
    }
  },
  methods:{
    async handleSubmit(){
      const response= await axios.post('https://site212224.tw.cs.unibo.it/auth/login/user', {
        username:this.username,
        password: this.password
      }).catch((err)=>{
        console.log('error:',err)
        this.error='wrong username or password'
      })
      console.log(response)
      localStorage.setItem('token', response.data.authority)

      if(localStorage.getItem('token')!==null){
        this.user=await axios.get(`https://site212224.tw.cs.unibo.it/user/username/${this.username}`)
            .then((response)=>{
              localStorage.setItem('username', response.data[0].username)
              localStorage.setItem('userid', response.data[0]._id)
              this.$store.dispatch('user', response.data[0])
            }).catch((err)=>{
              console.log('error:',err)
            })
      }
      console.log(localStorage.getItem('token'))
      console.log(localStorage.getItem('username'))
      this.$router.push('/')

    },
  },
}
</script>

<style scoped>
.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
  color:black;
}
.text-center {
  text-align: center!important;
  margin:0 auto ;
  width:30%;
  background-color: white;
  border-radius: 20px;
  border:1px solid var(--dark-alt)
}
@media (max-width: 768px) {
  .text-center{
    width:70%
  }
}
</style>
